ALTER TABLE `attr`
AUTO_INCREMENT=4;

ALTER TABLE `goods`
DROP COLUMN `name`,
CHANGE COLUMN `id` `goods_id`  int(11) NOT NULL COMMENT '商品id' FIRST ,
DROP PRIMARY KEY,
AUTO_INCREMENT=1;

ALTER TABLE `goods`
ADD COLUMN `id`  int(11) NOT NULL AUTO_INCREMENT FIRST ,
ADD PRIMARY KEY (`id`);

