select * from order where delivery_time
BETWEEN UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) AND (if(UNIX_TIMESTAMP(concat(cast(SYSDATE() AS DATE),' 12:00:00'))<UNIX_TIMESTAMP(),UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)+ INTERVAL 1 DAY),UNIX_TIMESTAMP(concat(cast(SYSDATE() AS DATE),' 12:00:00'))))
